language: python

python:
  - '2.7'

matrix:
  include:
    - python: 2.7
      env: JYTHON=org.python:jython-installer:2.5.3
      # env: JYTHON=org.python:jython-installer:2.5.3 FOO=foo


cache:
 directories:
   - $HOME/.m2
   - flink-1.5.2

install:
  - ls -lah flint-1.5.2 || echo "flink-1.5.2 directory not found"
  - if [ ! -d "flink-1.5.2" ]; then echo 'downloading...' && travis_retry curl -s http://mirrors.myaegean.gr/apache/flink/flink-1.5.2/flink-1.5.2-bin-scala_2.11.tgz | tar xzf -; fi
  - ./flink-1.5.2/bin/start-cluster.sh
  # - pip install unittest2

script:
  - ./flink-1.5.2/bin/pyflink-stream.sh example.py
  - grep -H "" flink-1.5.2/log/flink-*-taskexecutor-*.out
  # - python test.py

after_script:
  - ./flink-1.5.2/bin/stop-cluster.sh
